name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -o ./output

      - name: Copy to IIS folder
        run: |
          $source = "$(pwd)/output"
          $destination = "E:\NEWWEB\INCONTROL QA\InControl"
          
          # Crear la carpeta destino si no existe
          if (!(Test-Path -Path $destination)) {
            New-Item -ItemType Directory -Force -Path $destination
          }

          # Copiar los archivos compilados
          Copy-Item -Path $source\* -Destination $destination -Recurse -Force
        shell: powershell

