name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Navigate to the project directory
      working-directory: Intelica.Authentication.Backend/Intelica.Authentication.API
      run: pwd  # Verifica que estás en la carpeta correcta

    - name: Restore dependencies
      working-directory: Intelica.Authentication.Backend/Intelica.Authentication.API
      run: dotnet restore

    - name: Build
      working-directory: Intelica.Authentication.Backend/Intelica.Authentication.API
      run: dotnet build --no-restore

    - name: Test
      working-directory: Intelica.Authentication.Backend/Intelica.Authentication.API
      run: dotnet test --no-build --verbosity normal
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Intelica-Authentication-API
        path: Intelica.Authentication.Backend/publish

