name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Intelica.Authentication.Backend/Intelica.Authentication.API

    - name: Build and publish
      run: dotnet publish Intelica.Authentication.Backend/Intelica.Authentication.API -c Release -o ./output

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Intelica-Authentication-API
        path: ./output

  deploy:
    runs-on: sever-app
    needs: build 
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: Intelica-Authentication-API
      
      - name: Copy files to IIS folder
        run: |
          $source = "$(pwd)"
          $destination = "E:\NEWWEB"
            
          # Crear la carpeta destino si no existe
          if (!(Test-Path -Path $destination)) {
            New-Item -ItemType Directory -Force -Path $destination
          }
    
          # Copiar los archivos al destino
          Copy-Item -Path $source\* -Destination $destination -Recurse -Force
        shell: powershell
