name: Execute SQL Script

on:
  workflow_dispatch:

jobs:
  execute-sql:
    runs-on: db-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Execute SQL Script
      run: |
        # Define los parámetros de conexión
        $server = "172.0.2.213"
        $database = "ASSOCINCV"
        $user = "WEBDEVUSR"
        $password = "W3bdevusr"
        $scriptPath = "$(pwd)/script.sql"
    
        # Verifica que el archivo SQL existe
        if (!(Test-Path -Path $scriptPath)) {
          Write-Error "El archivo SQL no existe en la ruta especificada: $scriptPath"
        }
    
        # Ejecuta el script SQL usando sqlcmd
        sqlcmd -S 172.0.3.170\QA -d ASSOCINV -U WEBAPPUSR -P `"thAC18F4Lfn9rH75`" -b -i $scriptPath
      shell: pwsh
